Fixing PHPCS Errors (security-related)
TheGrove/woocommerce-gateway-converge pull request #14
Opened 2024-03-05 15:57 UTC by faisal-alvi

Closes #9

2024-03-06 23:07 UTC, dkotter requested changes

2024-03-06 23:07 UTC, dkotter commented on templates/cart/recurring-totals.php
> +					if ( 0 == $index && 'subtotal' == $key ) :
We may want to use strict comparison in this file, if possible

2024-03-06 23:07 UTC, dkotter commented on templates/cart/recurring-totals.php
> +						_e( 'Subtotal', 'elavon-converge-gateway' );
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on templates/checkout/payment-method.php
> +						<label for="<?php echo esc_html( WGC_KEY_SAVE_FOR_LATER_USE ); ?>"><?php esc_html_e( 'Save for later use', 'elavon-converge-gateway' ); ?></label>
Looks like a few attributes here that we should probably use `esc_attr` instead of `esc_html`

2024-03-06 23:07 UTC, dkotter commented on templates/checkout/payment-method.php
> +							<?php _e( 'Your info and card details will be saved. Subscriptions must be tied to your profile in order to process recurring payments.', 'elavon-converge-gateway' ); ?>
```suggestion
							<?php esc_html_e( 'Your info and card details will be saved. Subscriptions must be tied to your profile in order to process recurring payments.', 'elavon-converge-gateway' ); ?>
```

2024-03-06 23:07 UTC, dkotter commented on templates/checkout/recurring-totals.php
> +		<?php _e( 'Recurring Totals', 'elavon-converge-gateway' ); ?>
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on templates/checkout/recurring-totals.php
> +					if ( 0 == $index && 'subtotal' == $key ) :
More places we should look to use strict comparisons

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/change-payment-method.php
> +				<th><?php _e( 'Payment Method', 'elavon-converge-gateway' ); ?></th>
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/my-subscriptions.php
> +			<th><?php _e( 'Subscription', 'elavon-converge-gateway' ); ?></th>
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/my-subscriptions.php
> +	<?php printf( esc_html__( 'You have no subscriptions.', 'elavon-converge-gateway' ) ); ?>
Any need to use `printf` here?

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/view-subscription.php
> +<h1><?php echo esc_html_e( 'Converge subscription #', 'elavon-converge-gateway' ) . esc_html( $subscription->get_order_number() ); ?></h1>
We can either remove the `echo` statement here or use `esc_html__`

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/view-subscription.php
> +		<th><?php _e( 'Status', 'elavon-converge-gateway' ); ?></th>
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on templates/myaccount/view-subscription.php
> +	printf( esc_html__( 'There are no orders associated with this subscription.', 'elavon-converge-gateway' ) );
Another place I don't think we need to use `printf`

2024-03-06 23:07 UTC, dkotter commented on templates/order/subscription-details.php
> +<h2><?php _e( 'Related Converge subscriptions', 'elavon-converge-gateway' ); ?></h2>
More uses of `_e` that need updated in this file

2024-03-06 23:07 UTC, dkotter commented on phpcs.xml
> +<?xml version="1.0"?>
See we're adding a config file here. Should we also be setting up a GitHub Action to run PHPCS, similar to what we did for [ESLint](https://github.com/TheGrove/woocommerce-gateway-converge/pull/11)?

2024-03-07 12:37 UTC, faisal-alvi commented
@dkotter Thanks for the feedback. Based on the [assessment](https://10upwoo.wordpress.com/2024/02/07/woocommerce-extension-assessment-woocommerce-elavon-converge-eu-gateway/#complexity-maintainability), our strategy focuses solely on addressing security-related PHPCS errors and warnings. @iamdharmesh has compiled the list [here](https://gist.github.com/iamdharmesh/972a5eaa577bc913b2beb834102762b3), which aligns with our primary objective for this PR. As a result, some of the errors you provided feedback on were not initially included. Nonetheless, I have addressed them and any similar occurrences. Please review the changes in this commit: https://github.com/TheGrove/woocommerce-gateway-converge/pull/14/commits/8eaa40dd193b95dde6d997e55033e79395e05e5b

Regarding the setup of a GitHub Action for running PHPCS, integrating ESLint was straightforward since it's based on an npm package. However, PHPCS requires a composer package, which led to the removal of the existing `vendor` folder. Although I attempted to use the [WPCS action](https://github.com/10up/wpcs-action), it proved ineffective in this context. I then ended up adding a composer file, which resolved the issue. However, it's crucial to ensure that we don't run `composer install` during plugin builds. If we get the original composer, we can manage to add the required PHPCS dependency directly there and then we can get rid of this extra care.

2024-03-07 15:50 UTC, dkotter commented
> Based on the [assessment](https://10upwoo.wordpress.com/2024/02/07/woocommerce-extension-assessment-woocommerce-elavon-converge-eu-gateway/#complexity-maintainability), our strategy focuses solely on addressing security-related PHPCS errors and warnings

For future reference would be great to include this either in the Issue or the PR description, as I wasn't aware of this.

> Regarding the setup of a GitHub Action for running PHPCS, integrating ESLint was straightforward since it's based on an npm package. However, PHPCS requires a composer package, which led to the removal of the existing vendor folder. Although I attempted to use the [WPCS action](https://github.com/10up/wpcs-action), it proved ineffective in this context. I then ended up adding a composer file, which resolved the issue. However, it's crucial to ensure that we don't run composer install during plugin builds. If we get the original composer, we can manage to add the required PHPCS dependency directly there and then we can get rid of this extra care.

Because of the unique nature of how this repo is set up, what if instead of adding in `composer.json` and `composer.lock` files and then having to worry about accidentally removing the `vendor` directory, we could make our GitHub Action workflow install things itself.

So instead of running `composer install` during the action run, we could try something like:
```bash
composer require --dev sirbrillig/phpcs-changed -n
composer require --dev woocommerce/woocommerce-sniffs -n
```

Haven't tested that but I think it would work and keeps composer changes isolated to the workflow run

2024-03-07 15:54 UTC, dkotter requested changes

2024-03-07 15:54 UTC, dkotter commented on .github/workflows/phpcs.yml
> +        uses: tj-actions/changed-files@v35
Should use the latest version if possible:
```suggestion
        uses: tj-actions/changed-files@v42
```

2024-03-07 15:54 UTC, dkotter commented on .github/workflows/phpcs.yml
> +        run: composer install
Mentioned this in a comment but I think we could do something like:
```suggestion
        run: |
          composer require --dev sirbrillig/phpcs-changed -n
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require --dev woocommerce/woocommerce-sniffs -n
```

2024-03-07 16:11 UTC, faisal-alvi commented
> For future reference would be great to include this either in the Issue or the PR description, as I wasn't aware of this.

Correct! Excuse me, I'll make sure about that.

> Because of the unique nature of how this repo is set up, what if instead of adding in composer.json and composer.lock files and then having to worry about accidentally removing the vendor directory, we could make our GitHub Action workflow install things itself.

I removed the `composer.json` and `composer.lock` files and the workflow passed but we may need to check if it reports errors, right now no errors are there so it's clear. Should I add an intentional error to confirm?

2024-03-07 16:46 UTC, faisal-alvi commented
Okay so now I'm noticing that removing the composer files worked but now it (i.e `./vendor/bin/phpcs-changed`) does not consider the `phpcs.xml` file which is a must to exclude non-security related errors and warnings.

2024-03-07 16:47 UTC, faisal-alvi commented
Okay so now I'm noticing that removing the composer files worked but now it (i.e `./vendor/bin/phpcs-changed`) does not consider the `phpcs.xml` file which is a must to exclude non-security related errors and warnings.

2024-03-07 17:27 UTC, faisal-alvi commented
@dkotter this is ready for review, inline composer commands worked without any issues, thanks!

2024-03-07 17:42 UTC, dkotter approved these changes

2024-03-07 17:52 UTC, dkotter commented on assets/js/admin/subscription-details.js
>              action = 'wgc_sync_subscription_ajax_action';
Noticed this while merging this PR into the `smoke-testing` branch and resolving conflicts; we'll need a comma after this line, otherwise `nonce` won't be set up correctly

2024-03-08 11:19 UTC, faisal-alvi commented
Closing after #25

2024-03-08 11:19 UTC, closed without merging